application: fofou
version: 1
runtime: python
api_version: 1

handlers:
- url: /xn/.*
  script: gae-rest/xn.py
  
- url: /static
  static_dir: static

- url: /img
  static_dir: img

- url: .*
  script: main.py

